version: '3.8'

services:
  # Spring Boot 애플리케이션
  app:
    build: .
    container_name: kakao-clone-app
    ports:
      - "8080:8080"  # 로컬의 8080 포트를 컨테이너의 8080 포트에 연결
    depends_on:
      - mysql
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kakao-clone
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=minschive
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/kakao-clone

  # MySQL 서비스
  mysql:
    image: mysql:8.0
    container_name: kakao-clone-mysql
    environment:
      MYSQL_ROOT_PASSWORD: minschive
      MYSQL_DATABASE: kakao-clone
    ports:
      - "3305:3306"  # 로컬의 3305 포트를 컨테이너의 3306 포트에 연결
    volumes:
      - mysql-data:/var/lib/mysql


  # MongoDB 서비스
  mongodb:
    image: mongo:latest
    container_name: kakao-clone-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

# 데이터 볼륨 설정
volumes:
  mysql-data:
  mongo-data:
